import { Router } from 'express';
import authRoutes from './auth.routes.js';
import buildingRoutes from './building.routes.js';
import malfunctionRoutes from './malfunctions.routes.js';
import servicerRoutes from './servicers.routes.js';
const router = Router();
router.use('/auth', authRoutes);
router.use('/buildings', buildingRoutes);
router.use('/malfunctions', malfunctionRoutes);
router.use('/servicers', servicerRoutes);
export default router;
